#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("vplan.Resource", IsApplication=true)]

namespace vplan
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int btn = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_back = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_brightness_auto = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_overflow = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_refresh = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_web_site = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notifications = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060007
			public const int Image = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int backbtn = 2131099654;
			
			// aapt resource value: 0x7f06000e
			public const int browsebtn = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int btns = 2131099660;
			
			// aapt resource value: 0x7f060003
			public const int button1 = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int button2 = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int firstLine = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int header = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int icon = 2131099657;
			
			// aapt resource value: 0x7f060002
			public const int lv = 2131099650;
			
			// aapt resource value: 0x7f06000d
			public const int mainText = 2131099661;
			
			// aapt resource value: 0x7f060004
			public const int newsbtn = 2131099652;
			
			// aapt resource value: 0x7f06000b
			public const int scrollView1 = 2131099659;
			
			// aapt resource value: 0x7f060001
			public const int secondLine = 2131099649;
			
			// aapt resource value: 0x7f06000a
			public const int title = 2131099658;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int list_row = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int News = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int news_row = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int NewsItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Settings = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int AppTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
